/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginandsignup;

 
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class Dashboard extends javax.swing.JFrame {

     Connection conn = null;
    PreparedStatement pst = null;       
    
    public Dashboard() {
        initComponents();
        conn = DBconnect.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nicbox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fullnamebox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        address1 = new javax.swing.JTextField();
        address2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        officebox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        categorybox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        CheckBox1 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        CheckBox2 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        lengthbox = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textarea1 = new javax.swing.JTextArea();
        button1 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        clearbutton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("coustomer FullName");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        nicbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicboxActionPerformed(evt);
            }
        });
        jPanel2.add(nicbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 160, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("coustomer NIC");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));
        jPanel2.add(fullnamebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 210, -1));

        jLabel3.setText("Address line 1 ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel4.setText("Address line 2");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));
        jPanel2.add(address1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 200, -1));
        jPanel2.add(address2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 200, -1));

        jLabel5.setText("Office");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        officebox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kegalle ", "Mawanella ", "Rambukkana", "Aranayaka ", "Kandy ", "Rathnapura " }));
        jPanel2.add(officebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        jLabel6.setText("category");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        categorybox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10-Domestic", "71-Commercial", "81-School", "77- Religion" }));
        categorybox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryboxActionPerformed(evt);
            }
        });
        jPanel2.add(categorybox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        jLabel7.setText("Under Construction");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        CheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(CheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, -1));

        jLabel8.setText("Exavation done by contructor");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        CheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox2ActionPerformed(evt);
            }
        });
        jPanel2.add(CheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, -1, -1));

        jLabel9.setText("Pipe Length");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));
        jPanel2.add(lengthbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 90, -1));

        textarea1.setColumns(20);
        textarea1.setRows(5);
        jScrollPane1.setViewportView(textarea1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 450, 470));

        button1.setText("ADD");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel2.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        button2.setText("Edit Previous one ");
        jPanel2.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        button3.setText("Print ");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        jPanel2.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 510, -1, -1));

        clearbutton.setText("Clear");
        clearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(clearbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, -1, -1));

        jLabel10.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Company Name");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 880, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 895, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBox2ActionPerformed

    private void CheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBox1ActionPerformed

    private void categoryboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryboxActionPerformed

    private void nicboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicboxActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
       String nic = nicbox.getText();
       String fullname = fullnamebox.getText();
        String addressLine1 = address1.getText();
        String addressLine2 = address2.getText();
        String office = (String) officebox.getSelectedItem();
        String category = (String) categorybox.getSelectedItem();
        boolean underConstruction = CheckBox1.isSelected();
        boolean excavationByContractor = CheckBox2.isSelected();
        int pipeLength = Integer.parseInt(lengthbox.getText());
        
        
        double basicCost = 19250.00;
        if (pipeLength > 10 && pipeLength <= 24){
            basicCost = 19450.00;
        } else if (pipeLength > 24){
            basicCost = 19250.00 + 5000;
        }
        double additionalCost = 0.0;
        if (underConstruction){
            additionalCost += 5000;
          
        }
        if(excavationByContractor){
            additionalCost +=5000;
        }
      double totalCost = basicCost + additionalCost;
      
      

    // store data in a database;
    String sql = "INSERT INTO estimate_details (nic, fullname, address1, address2, office, pipe_length, under_construction, contractor_excavation, total_cost) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
    
    try {
        pst = conn.prepareStatement(sql);
        pst.setString(1, nic);
        pst.setString(2, fullname);
        pst.setString(3, addressLine1);
        pst.setString(4, addressLine2);
        pst.setString(5, office);
        pst.setInt(6, pipeLength);
        pst.setBoolean(7, underConstruction);
        pst.setBoolean(8, excavationByContractor);
        pst.setDouble(9, totalCost);

        pst.executeUpdate();
    } catch (SQLException e) {
        e.printStackTrace();
    }    

        
        String companyName = "NWSDB";
String telNo = "0352246014";
String sentence = "Pay in voucher for new water connection";

// Prepare the full address
String fullAddress = addressLine1 + ", " + addressLine2;

// Construct the bill
StringBuilder bill = new StringBuilder();
bill.append("*******************************\n");
bill.append(companyName).append("\n");
bill.append("Tel: ").append(telNo).append("\n");
bill.append("*******************************\n\n");
bill.append(sentence).append("\n\n");

bill.append("Customer Details:\n");
bill.append("-------------------------\n");
bill.append(String.format("%-15s: %s\n", "NIC", nic));
bill.append(String.format("%-15s: %s\n", "Full Name", fullname));
bill.append(String.format("%-15s: %s\n", "Address", fullAddress));
bill.append(String.format("%-15s: %s\n", "Category", category));
bill.append(String.format("%-15s: %d meters\n", "Pipe Length", pipeLength));
bill.append(String.format("%-15s: %s\n", "Office", office));
bill.append("\n");

bill.append("Cost Details:\n");
bill.append("-------------------------\n");
bill.append(String.format("%-15s: Rs. %.2f\n", "Basic Cost", basicCost));
bill.append(String.format("%-15s: Rs. %.2f\n", "Additional Cost", additionalCost));
bill.append(String.format("%-15s: Rs. %.2f\n", "Total Cost", totalCost));
bill.append("\n");

bill.append("Bank Details:\n");
bill.append("-------------------------\n");
bill.append("BOC Kegalle - 9278595\n");
bill.append("By Cash Only\n\n");

bill.append("Prepared by:__________________\n");
bill.append("OIC:__________________________\n");
bill.append("Date:_________________________\n");

// Display the bill in the textarea
textarea1.setText(bill.toString());
    
    }//GEN-LAST:event_button1ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
               try {
            textarea1.print();
        } catch (java.awt.print.PrinterException e) {
            System.err.format("No printer found", e.getMessage());
        }
    }//GEN-LAST:event_button3ActionPerformed

    private void clearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbuttonActionPerformed
        
         nicbox.setText("");
    fullnamebox.setText("");
    address1.setText("");
    address2.setText("");
    officebox.setSelectedIndex(0);
    categorybox.setSelectedIndex(0);
    CheckBox1.setSelected(false);
    CheckBox2.setSelected(false);
    lengthbox.setText("");
    textarea1.setText("");
    }//GEN-LAST:event_clearbuttonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
             } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBox1;
    private javax.swing.JCheckBox CheckBox2;
    private javax.swing.JTextField address1;
    private javax.swing.JTextField address2;
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JComboBox<String> categorybox;
    private javax.swing.JButton clearbutton;
    private javax.swing.JTextField fullnamebox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lengthbox;
    private javax.swing.JTextField nicbox;
    private javax.swing.JComboBox<String> officebox;
    private javax.swing.JTextArea textarea1;
    // End of variables declaration//GEN-END:variables
}
